---
# tasks file for ajgarlag.bootstrap
- import_tasks: packages.yml
- import_tasks: sudo.yml
- import_tasks: ssh.yml
- import_tasks: ufw.yml
- import_tasks: rkhunter.yml
- import_tasks: exim4relay.yml
  when: ajgarlag_bootstrap_exim4relay
- import_tasks: aliases.yml
