---
# tasks file for ajgarlag.bootstrap
- name: installing bootstrap packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items: '{{ ajgarlag_bootstrap_packages }}'

- name: creating sudoer user
  user:
    name: '{{ ajgarlag_bootstrap_sudoer_user }}'
  when: ajgarlag_bootstrap_sudoer_user != ""

- name: adding user as sudoer
  copy:
    content: '{{ ajgarlag_bootstrap_sudoer_user }} ALL=(ALL) {%if not ajgarlag_bootstrap_sudoer_user_require_password%}NO{%endif%}PASSWD: ALL'
    dest: /etc/sudoers.d/{{ ajgarlag_bootstrap_sudoer_user }}
    owner: root
    group: root
    mode: 0440
  when: ajgarlag_bootstrap_sudoer_user != ""

- name: setting up current user authorized key
  authorized_key:
    user: '{{ ajgarlag_bootstrap_ssh_key_user }}'
    key: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'
  when: ajgarlag_bootstrap_add_current_user_key

- name: setting up extra authorized keys
  authorized_key:
    user: '{{ ajgarlag_bootstrap_ssh_key_user }}'
    key: '{{ item }}'
  with_items: '{{ ajgarlag_bootstrap_extra_authorized_keys }}'

- name: configuring SSH root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin {%if ajgarlag_bootstrap_root_login == "without-password" %}without-password{% elif ajgarlag_bootstrap_root_login|bool %}yes{% else %}no{% endif %}'
    regexp: '^PermitRootLogin '
  notify:
    - reload ssh

- name: configuring SSH password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication {%if ajgarlag_bootstrap_password_login %}yes{% else %}no{% endif %}'
    regexp: '^PasswordAuthentication '
  notify:
    - reload ssh

- name: allowing SSH connections
  ufw:
    rule: allow
    proto: tcp
    port: 22

- name: setting ufw default state
  ufw:
    state: '{%if ajgarlag_bootstrap_ufw_enable %}enabled{% else %}disabled{% endif %}'
