---
# tasks file for ajgarlag.bootstrap
- include: packages.yml
- include: sudo.yml
- include: ssh.yml
- include: ufw.yml
- include: rkhunter.yml
- include: exim4relay.yml
  when: ajgarlag_bootstrap_exim4relay
- include: aliases.yml
