---
# tasks file for ajgarlag.bootstrap
- name: installing bootstrap packages
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items: ajgarlag_bootstrap_packages

- name: setting up current user authorized key
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: ajgarlag_bootstrap_add_current_user_key

- name: setting up extra authorized key
  authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ item }}"
  with_items: ajgarlag_bootstrap_extra_authorized_keys
