---
# tasks file for ajgarlag.bootstrap
- name: installing bootstrap packages
  apt:
    pkg: '{{ item }}'
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  with_items: '{{ ajgarlag_bootstrap_packages }}'

- name: creating sudoer user
  user:
    name: '{{ ajgarlag_bootstrap_sudoer_user }}'
  when: ajgarlag_bootstrap_sudoer_user != ""

- name: adding user as sudoer
  copy:
    content: '{{ ajgarlag_bootstrap_sudoer_user }} ALL=(ALL) {%if not ajgarlag_bootstrap_sudoer_user_require_password%}NO{%endif%}PASSWD: ALL'
    dest: /etc/sudoers.d/{{ ajgarlag_bootstrap_sudoer_user }}
    owner: root
    group: root
    mode: 0440
  when: ajgarlag_bootstrap_sudoer_user != ""

- name: setting up current user authorized key
  authorized_key:
    user: '{{ ajgarlag_bootstrap_ssh_key_user }}'
    key: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'
  when: ajgarlag_bootstrap_add_current_user_key

- name: setting up extra authorized keys
  authorized_key:
    user: '{{ ajgarlag_bootstrap_ssh_key_user }}'
    key: '{{ item }}'
  with_items: '{{ ajgarlag_bootstrap_extra_authorized_keys }}'

- name: disabling SSH root login with password
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin without-password'
    regexp: '^PermitRootLogin '
  notify:
    - reload ssh
  when: ajgarlag_bootstrap_disable_ssh_root_password_login

- name: disabling SSH login with password
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication no'
    regexp: '^PasswordAuthentication '
  notify:
    - reload ssh
  when: ajgarlag_bootstrap_disable_ssh_password_login

- name: allowing SSH connections
  ufw:
    rule: allow
    proto: tcp
    port: 22

- name: enabling ufw
  ufw:
    state: enabled
  when: ajgarlag_bootstrap_ufw_enable
