- name: setting up current user authorized key
  authorized_key:
    user: '{{ ajgarlag_bootstrap_ssh_key_user }}'
    key: '{{ lookup("file", "~/.ssh/id_rsa.pub") }}'
  when: ajgarlag_bootstrap_ssh_authorize_current_user_key

- name: setting up extra authorized keys
  authorized_key:
    user: '{{ ajgarlag_bootstrap_ssh_key_user }}'
    key: '{{ item }}'
  with_items: '{{ ajgarlag_bootstrap_ssh_extra_authorized_keys }}'

- name: configuring SSH root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitRootLogin {%if ajgarlag_bootstrap_ssh_allow_root_login == "without-password" %}without-password{% elif ajgarlag_bootstrap_ssh_allow_root_login|bool %}yes{% else %}no{% endif %}'
    regexp: '^[\s#]*PermitRootLogin '
  notify:
    - reload ssh

- name: configuring SSH password login
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PasswordAuthentication {%if ajgarlag_bootstrap_ssh_allow_password_login %}yes{% else %}no{% endif %}'
    regexp: '^[\s#]*PasswordAuthentication '
  notify:
    - reload ssh
