- name: installing sudo package
  apt:
    pkg: sudo
    state: latest

- name: creating sudoer user
  user:
    name: '{{ ajgarlag_bootstrap_sudo_sudoer }}'
  when: ajgarlag_bootstrap_sudo_sudoer != ""

- name: adding user as sudoer
  copy:
    content: '{{ ajgarlag_bootstrap_sudo_sudoer }} ALL=(ALL) {%if not ajgarlag_bootstrap_sudo_require_password%}NO{%endif%}PASSWD: ALL'
    dest: /etc/sudoers.d/{{ ajgarlag_bootstrap_sudo_sudoer }}
    owner: root
    group: root
    mode: 0440
  when: ajgarlag_bootstrap_sudo_sudoer != ""
