---
# tasks file for ajgarlag.bootstrap
- include_tasks: packages.yml
- include_tasks: sudo.yml
- include_tasks: ssh.yml
- include_tasks: ufw.yml
- include_tasks: rkhunter.yml
- include_tasks: exim4relay.yml
  when: ajgarlag_bootstrap_exim4relay
- include_tasks: aliases.yml
