---
language: python
sudo: required

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

before_script:
  # Generate a SSH key
  - ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

  # Link the current directory to the role name
  - ln -s $PWD ../ajgarlag.bootstrap

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook -i tests/inventory tests/test.yml --syntax-check"

  # Run the role/playbook with ansible-playbook.
  - "ansible-playbook -i tests/inventory tests/test.yml --connection=local --become"

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i tests/inventory tests/test.yml --connection=local --become
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Check default packages are installed
  - "for package in python-apt python-pycurl lsb-release fail2ban ufw ; do dpkg -s $package; done"

  # Check ufw is running
  - "sudo service ufw status"
